version: '3.9'

services:
  db:
    image: postgres
    hostname: db
    extra_hosts:
      - "dev.db:192.168.178.73"
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - 'postgres:/var/lib/postgresql/data'
  pgadmin:
    image: dpage/pgadmin4
    hostname: pgadmin
    ports:
      - "5584:80"
    env_file:
      - .env
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    depends_on:
      - db

volumes:
  postgres:
    driver: local
  pgadmin:
    driver: local